# Generated by Django 5.0.6 on 2024-05-27 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='english',
            new_name='english_word',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='polish',
            new_name='polish_word',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
