# Generated by Django 5.0.6 on 2024-05-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='polish_word',
            field=models.CharField(max_length=100),
        ),
    ]
