# Generated by Django 5.0.6 on 2024-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_remove_word_created_at_alter_word_english_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='set_number',
            field=models.IntegerField(default=1),
        ),
    ]
